# Generated by Django 5.2.6 on 2025-09-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='imagem_capa',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_capa/'),
        ),
    ]
