# Generated by Django 5.2.7 on 2025-10-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_noticia_imagem_capa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='imagem_capa',
            field=models.ImageField(blank=True, null=True, upload_to='media/imagens_capa/'),
        ),
    ]
