# Generated by Django 5.2.7 on 2025-10-02 01:55

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_alter_noticia_imagem_capa'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='autor_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='conteudo',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagem_capa',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_capa/'),
        ),
    ]
